region = "central1"
project_id = "intrado-cloudrun-testing"
zonename = "gcp-lab-perficientdevops"
domain = "gcp.lab.perficientdevops.com."
subdomain = "gcp.lab.perficientdevops.com"
credfile = "intrado-cloudrun-testing-3282f442a7cd.json"
servicename = "helloservice"
